# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: deployquest
  labels:
    app: deployquest
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: deployquest
  type: ClusterIP